[WARNING] [2020-06-05 03:21:49,825:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:21:49,842:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:21:51,845:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:21:53,849:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:21:55,852:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:21:57,855:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:21:59,858:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:01,862:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:03,865:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:05,868:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:07,871:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:09,874:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:11,877:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:13,881:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:15,884:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:17,887:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:19,890:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:22:21,894:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] No models better than random - using Dummy Score!
[WARNING] [2020-06-05 03:36:47,206:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Memory Exception -- restart with less ensemle_nbest: 25
[WARNING] [2020-06-05 03:36:47,581:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Memory Exception -- restart with less ensemle_nbest: 12
[WARNING] [2020-06-05 03:36:47,934:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Memory Exception -- restart with less ensemle_nbest: 6
[WARNING] [2020-06-05 04:48:50,828:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Memory Exception -- restart with less ensemle_nbest: 3
[WARNING] [2020-06-05 04:48:51,074:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_47.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError

[WARNING] [2020-06-05 04:48:51,082:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_46.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,096:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_44.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
    loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,111:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_43.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
    score = metric(solution, prediction)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2140, in log_loss
    transformed_labels = lb.transform(y_true)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/preprocessing/label.py", line 470, in transform
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/preprocessing/label.py", line 657, in label_binarize
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/scipy/sparse/compressed.py", line 1025, in toarray
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/scipy/sparse/base.py", line 1189, in _process_toarray_args
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type int64

[WARNING] [2020-06-05 04:48:51,120:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_42.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,129:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_41.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,138:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_40.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,147:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_39.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,157:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_38.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,166:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_36.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,175:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_35.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,184:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_34.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,193:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_33.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,203:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_32.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,212:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_31.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,221:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_30.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,230:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_29.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,239:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_25.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,248:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_24.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,257:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_23.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,266:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_22.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,275:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_21.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,284:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_20.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,294:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_18.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,303:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_17.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,313:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_15.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,323:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_14.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,332:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_12.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,341:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_11.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,351:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_9.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,360:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_8.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,369:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_7.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,379:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_6.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,388:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_5.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,397:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_4.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,406:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_3.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,415:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_2.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:51,424:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,644:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_23.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,650:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_22.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,657:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_21.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,665:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_20.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,671:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_18.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,678:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_17.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,684:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_15.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,690:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_14.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,697:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_12.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,704:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_11.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,713:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_9.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,719:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_8.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,726:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_7.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,731:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_6.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,738:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_5.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,744:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_4.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,751:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_3.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,757:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_2.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:52,763:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

[WARNING] [2020-06-05 04:48:53,664:EnsembleBuilder(1):cd5aedb03fc220f899d01d8322c6ccad] Error loading /tmp/autosklearn_tmp_30855_8801/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 323, in read_ensemble_preds
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 306, in calculate_score
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/metrics/__init__.py", line 97, in __call__
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 2174, in log_loss
MemoryError: Unable to allocate 205. KiB for an array with shape (8739, 3) and data type float64

Log_loss score 0.17321338709688158
